import React, { useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import { getCurrentUser, sendLoginCode, signOut, verifyLoginCode } from './services/auth';
import { recordRecovery, submitOrder } from './services/supabase-transactions';
import type { User } from './types';

type Row = Record<string, any>;
type Tab = 'dashboard'|'orders'|'invoices'|'ledger'|'recovery'|'customers'|'products';
const money=(n:any)=>`PKR ${Number(n||0).toLocaleString('en-PK',{maximumFractionDigits:2})}`;
const date=(v:any)=>v?new Date(v).toLocaleDateString('en-GB'):'-';

function Login(){
 const[email,setEmail]=useState(''),[code,setCode]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function send(){setBusy(true);setError('');try{await sendLoginCode(email);setSent(true)}catch(e:any){setError(e.message||'Unable to send code.')}finally{setBusy(false)}}
 async function verify(){setBusy(true);setError('');try{await verifyLoginCode(email,code);location.reload()}catch(e:any){setError(e.message||'Invalid code.')}finally{setBusy(false)}}
 return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">NL</div><h1>N-LINK 360</h1><p>Dealer & Distributor Sales Operations</p><label>Registered corporate email</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@company.com" disabled={sent}/>{sent&&<><label>Verification code</label><input value={code} onChange={e=>setCode(e.target.value)} inputMode="numeric" placeholder="Enter code"/></>}{error&&<div className="error">{error}</div>}<button disabled={busy||!email||(sent&&!code)} onClick={sent?verify:send}>{busy?'Please wait…':sent?'Verify & sign in':'Send verification code'}</button>{sent&&<button className="secondary" onClick={()=>{setSent(false);setCode('')}}>Change email</button>}</section></main>
}

export default function App(){
 const[user,setUser]=useState<User|null>(null),[checking,setChecking]=useState(true);
 useEffect(()=>{getCurrentUser().then(setUser).catch(console.error).finally(()=>setChecking(false))},[]);
 if(checking)return <div className="loading">Connecting to N-LINK 360…</div>;
 return user?<Workspace user={user}/>:<Login/>;
}

function Workspace({user}:{user:User}){
 const[tab,setTab]=useState<Tab>('dashboard'),[data,setData]=useState<Record<string,Row[]>>({customers:[],products:[],skus:[],orders:[],invoices:[],recoveries:[],ledger:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{if(!supabase)return;setLoading(true);setError('');try{const q=async(t:string)=>{const r=await supabase!.from(t).select('*');if(r.error)throw r.error;return r.data||[]};const [customers,products,skus,orders,invoices,recoveries,ledger]=await Promise.all([q('customers'),q('products'),q('skus'),q('sales_orders'),q('invoices'),q('recoveries'),q('ledger_entries')]);setData({customers,products,skus,orders,invoices,recoveries,ledger})}catch(e:any){setError(e.message||'Production database read failed.')}finally{setLoading(false)}};
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),60000);return()=>clearInterval(timer)},[]);
 const stats=useMemo(()=>({sales:data.invoices.reduce((s,x)=>s+Number(x.invoice_amount||0),0),recovery:data.recoveries.filter(x=>['APPROVED','VERIFIED'].includes(x.status)).reduce((s,x)=>s+Number(x.amount||0),0),outstanding:data.customers.reduce((s,x)=>s+Number(x.current_balance??x.opening_balance??0),0),accounts:data.customers.filter(x=>x.status).length}),[data]);
 const nav:[Tab,string][]=[['dashboard','Command Center'],['orders','Orders'],['invoices','Invoices'],['ledger','Live Ledger'],['recovery','Recovery'],['customers','Dealers / Distributors'],['products','Products / SKUs']];
 return <div className="app"><header><div><div className="brand">N-LINK <span>360</span></div><small>Production Sales & Recovery Control</small></div><div className="user"><b>{user.fullName}</b><span>{user.role}</span><button onClick={()=>{void signOut();setUserNull()}}>Sign out</button></div></header><nav>{nav.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav><main className="content">{notice&&<div className="notice">{notice}</div>}{error&&<div className="error">{error}</div>}{loading?<div className="loading-panel">Loading real production data…</div>:<>{tab==='dashboard'&&<Dashboard stats={stats} data={data} setTab={setTab}/>} {tab==='orders'&&<Orders data={data} refresh={load} notice={setNotice}/>} {tab==='invoices'&&<Table title="Invoices" rows={data.invoices} columns={['invoice_code','invoice_date','customer_id','invoice_amount','status']}/>} {tab==='ledger'&&<Table title="Live Customer Ledger" rows={data.ledger} columns={['ledger_code','entry_date','customer_id','reference_type','debit','credit','running_balance']}/>} {tab==='recovery'&&<Recovery data={data} refresh={load} notice={setNotice}/>} {tab==='customers'&&<Table title="Dealers & Distributors" rows={data.customers} columns={['customer_code','name','customer_type','mobile','city','credit_limit','credit_days','opening_balance','status']}/>} {tab==='products'&&<Table title="Products" rows={data.products} columns={['product_code','name','model','wattage','status']}/>}</>}</main></div>;
 function setUserNull(){location.reload()}
}

function Dashboard({stats,data,setTab}:{stats:any,data:any,setTab:(t:Tab)=>void}){return <><section className="hero"><div><span className="eyebrow">LIVE PRODUCTION DATA</span><h2>Dealer & Distributor Command Center</h2><p>No seeded demo records. Metrics come directly from Supabase.</p></div><button onClick={()=>setTab('orders')}>Create Sales Order</button></section><div className="metrics"><Metric label="Invoiced Sales" value={money(stats.sales)}/><Metric label="Verified Recovery" value={money(stats.recovery)}/><Metric label="Outstanding" value={money(stats.outstanding)}/><Metric label="Active Accounts" value={stats.accounts}/></div><div className="grid2"><Panel title="Recent Orders"><Table rows={data.orders.slice(0,10)} columns={['order_code','order_date','customer_id','requested_amount','status']}/></Panel><Panel title="Recent Recoveries"><Table rows={data.recoveries.slice(0,10)} columns={['recovery_code','recovery_date','customer_id','amount','payment_method','status']}/></Panel></div></>}
function Metric({label,value}:{label:string,value:any}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><h3>{title}</h3>{children}</section>}

function Orders({data,refresh,notice}:{data:any,refresh:()=>Promise<void>,notice:(s:string)=>void}){const[customerId,setCustomerId]=useState(''),[lines,setLines]=useState([{skuId:'',qty:1,price:0}]),[busy,setBusy]=useState(false);const skus=data.skus||[];const setLine=(i:number,k:string,v:any)=>setLines(a=>a.map((x,j)=>j===i?{...x,[k]:v}:x));const total=lines.reduce((s,x)=>s+Number(x.qty||0)*Number(x.price||0),0);async function save(){if(!customerId||!lines.every(x=>x.skuId&&x.qty>0))return;setBusy(true);try{const id=await submitOrder({customerId,items:lines.map(x=>({skuId:x.skuId,orderedQuantity:Number(x.qty),unitPrice:Number(x.price)})),totalAmount:total} as any);notice(`Order ${id} saved to the production database.`);setCustomerId('');setLines([{skuId:'',qty:1,price:0}]);await refresh()}catch(e:any){notice(`Order failed: ${e.message||e}`)}finally{setBusy(false)}}return <section className="panel form-panel"><h2>Dealer / Distributor Sales Order</h2><label>Account<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select active account</option>{data.customers.filter((x:any)=>x.status).map((x:any)=><option key={x.id} value={x.id}>{x.customer_code} · {x.name} · {x.customer_type}</option>)}</select></label>{lines.map((l,i)=><div className="line" key={i}><select value={l.skuId} onChange={e=>{const s=skus.find((x:any)=>x.id===e.target.value);setLine(i,'skuId',e.target.value);setLine(i,'price',Number(s?.dealer_price??s?.trade_price??s?.sale_price??0))}}><option value="">Select SKU</option>{skus.filter((x:any)=>x.status).map((s:any)=><option key={s.id} value={s.id}>{s.sku_code} · {s.sku_name}</option>)}</select><input type="number" min="1" value={l.qty} onChange={e=>setLine(i,'qty',Number(e.target.value))}/><input type="number" min="0" step="0.01" value={l.price} onChange={e=>setLine(i,'price',Number(e.target.value))}/>{lines.length>1&&<button className="danger" onClick={()=>setLines(a=>a.filter((_,j)=>j!==i))}>×</button>}</div>)}<button className="secondary" onClick={()=>setLines(a=>[...a,{skuId:'',qty:1,price:0}])}>+ Add SKU</button><div className="total">Order total <b>{money(total)}</b></div><button disabled={busy||!customerId} onClick={save}>{busy?'Saving…':'Submit real order'}</button></section>}

function Recovery({data,refresh,notice}:{data:any,refresh:()=>Promise<void>,notice:(s:string)=>void}){const[customerId,setCustomerId]=useState(''),[amount,setAmount]=useState(0),[mode,setMode]=useState('CASH'),[busy,setBusy]=useState(false);async function save(){setBusy(true);try{const id=await recordRecovery({customerId,amount,paymentMode:mode as any});notice(`Recovery ${id} recorded in production. It remains subject to the configured verification workflow.`);setCustomerId('');setAmount(0);await refresh()}catch(e:any){notice(`Recovery failed: ${e.message||e}`)}finally{setBusy(false)}}return <div className="grid2"><section className="panel form-panel"><h2>Record Recovery</h2><label>Account<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Select account</option>{data.customers.map((x:any)=><option key={x.id} value={x.id}>{x.customer_code} · {x.name}</option>)}</select></label><label>Amount<input type="number" min="0.01" step="0.01" value={amount||''} onChange={e=>setAmount(Number(e.target.value))}/></label><label>Payment mode<select value={mode} onChange={e=>setMode(e.target.value)}><option>CASH</option><option>CHEQUE</option><option>ONLINE_TRANSFER</option><option>BANK_TRANSFER</option></select></label><button disabled={!customerId||amount<=0||busy} onClick={save}>{busy?'Saving…':'Record recovery'}</button></section><Panel title="Recent Recoveries"><Table rows={data.recoveries.slice(0,15)} columns={['recovery_code','recovery_date','customer_id','amount','payment_method','status']}/></Panel></div>}

function Table({title,rows,columns}:{title?:string,rows:Row[],columns:string[]}){return <div className="table-wrap">{title&&<h2>{title}</h2>}<table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{columns.map(c=><td key={c}>{c.includes('date')||c.endsWith('_at')?date(r[c]):['amount','balance','price','debit','credit','limit'].some(x=>c.includes(x))?money(r[c]):String(r[c]??'-')}</td>)}</tr>):<tr><td className="empty" colSpan={columns.length}>No production records found.</td></tr>}</tbody></table></div>}
